"""empty message

Revision ID: ec0b4ba4f480
Revises: 
Create Date: 2020-10-14 20:38:45.390036

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec0b4ba4f480'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('shares')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shares',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shares_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('shares_no', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('total_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='shares_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='shares_pkey')
    )
    op.create_table('history',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('shares_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('shares_no', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='history_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='history_pkey')
    )
    # ### end Alembic commands ###
